name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Automatic Releases
      uses: Fulminazzo/java-automatic-release@v4
      with:
        java-version: '8'

    - name: Build & Test
      run: |
        ./gradlew build
