steps:
      
      - name: Checkout source
        uses: actions/checkout@v4

      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      
      - name: Build with Gradle
        run: ./gradlew build

      
      - name: Package build output
        run: |
          mkdir package
          cp build/libs/*.jar package/
          cp README.md package/ || true   # example: include extra files
          zip -r my-app.zip package

      
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-zip
          path: my-app.zip
